FROM kasmweb/core:1.6.0
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME

######### Customize Container Here ###########


# Install Firefox
COPY ./src/ubuntu/install/firefox/ $INST_SCRIPTS/firefox/
COPY ./src/ubuntu/install/firefox/firefox.desktop $HOME/Desktop/
RUN bash $INST_SCRIPTS/firefox/install_firefox.sh && rm -rf $INST_SCRIPTS/firefox/

# Enabled Single Application Mode - No desktop environment will be spawned
ENV SINGLE_APPLICATION=1

# Setup the custom startup script that will be invoked when the container starts
ENV LAUNCH_URL  http://kasmweb.com
RUN echo $' \n\
set -x \n\
FORCE=$2 \n\
URL=${1:-$LAUNCH_URL}  \n\
if [ -n "$URL" ] && ( [ -z "$DISABLE_CUSTOM_STARTUP" ] ||  [ -n "$FORCE" ] ) ; then \n\
    if [ -f /tmp/custom_startup.lck ] ; then  \n\
        echo "custom_startup already running!" \n\
        exit 1 \n\
    fi \n\
    touch /tmp/custom_startup.lck \n\
    while true \n\
    do \n\
        if ! pgrep -x firefox > /dev/null \n\
        then \n\
            firefox -width ${VNC_RESOLUTION/x*/} -height ${VNC_RESOLUTION/*x/} $URL \n\
        fi \n\
        sleep 1 \n\
    done \n\
    rm /tmp/custom_startup.lck \n\
fi \n\
' >$STARTUPDIR/custom_startup.sh
RUN chmod +x $STARTUPDIR/custom_startup.sh


######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
